#!/bin/bash
set -x

echo "=> enable quemu"
docker run --rm --privileged multiarch/qemu-user-static:register --reset

VERSION=$(cat VERSION)
chmod +x mkimage-alpine.sh

docker run --rm -t -e ARCH=armhf -w /data -v $(pwd):/data hypriot/rpi-alpine:3.4 sh -c \
"apk add -U curl tar && ./mkimage-alpine.sh -s -r ${VERSION}"

ls -lA .
